# .streamlit/config.toml

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
headless = true

# Hide the "Made with Streamlit" watermark
hideStreamlitBranding = true